#pragma once
#ifndef _TINYPBRT_ERROR_H_
#define _TINYPBRT_ERROR_H_

#include <tinypbrt/detail/fwd.h>

#ifdef __cplusplus
extern "C" {
#endif

	typedef enum tpbrt_error_t : uint8_t {
		TPBRT_ERROR_NONE									  = 0,
		TPBRT_ERROR_END_OF_FILE								  = 1,
		TPBRT_ERROR_INVALID_TOKEN							  = 2,
		TPBRT_ERROR_PARSE_FLOAT								  = 3,
		TPBRT_ERROR_PARSE_INT								  = 4,
		TPBRT_ERROR_PARSE_BOOL								  = 5,
		TPBRT_ERROR_UNKNOWN_DIRECTIVE						  = 6,
		TPBRT_ERROR_INVALID_STRING							  = 7,
		TPBRT_ERROR_UNKNOWN_OPTION							  = 8,
		TPBRT_ERROR_UNKNOWN_COORDINATE_SYSTEM				  = 9,
		TPBRT_ERROR_INVALID_PARAM_NAME						  = 10,
		TPBRT_ERROR_INVALID_PARAM_TYPE						  = 11,
		TPBRT_ERROR_DUPLICATE_PARAM_NAME					  = 12,
		TPBRT_ERROR_WORLD_ALREADY_STARTED					  = 13,
		TPBRT_ERROR_TOO_MANY_END_ATTRIBUTES					  = 14,
		TPBRT_ERROR_INVALID_OBJECT_TYPE						  = 15,
		TPBRT_ERROR_UNEXPECTED_TOKEN						  = 16,
		TPBRT_ERROR_MISSING_REQUIRED_PARAMETER				  = 17,
		TPBRT_ERROR_NOT_FOUND								  = 18,
		TPBRT_ERROR_OUT_OF_MEMORY							  = 19,
		TPBRT_ERROR_INVALID_POINTER							  = 20,
		TPBRT_ERROR_INVALID_FILM_TYPE						  = 21,
		TPBRT_ERROR_PARSE_UINT								  = 22,
		TPBRT_ERROR_UNKNOWN_COLOR_SPACE						  = 23,
		TPBRT_ERROR_UNKNOWN_SPECTRUM_BUILTIN				  = 24,
		TPBRT_ERROR_TOO_MANY_VALUES							  = 25,
		TPBRT_ERROR_UNKNOWN_FILM_SENSOR						  = 26,
		TPBRT_ERROR_UNKNOWN_CAMERA_TYPE						  = 27,
		TPBRT_ERROR_UNKNOWN_CAMERA_SPHERICAL_MAPPING		  = 28,
		TPBRT_ERROR_UNKNOWN_CAMERA_REALISTIC_APERTURE_BUILTIN = 29,
		TPBRT_ERROR_UNKNOWN_INTEGRATOR_TYPE					  = 30,
		TPBRT_ERROR_UNKNOWN_INTEGRATOR_LIGHT_SAMPLER		  = 31,
		TPBRT_ERROR_UNKNOWN_ACCELERATOR_TYPE				  = 32,
		TPBRT_ERROR_UNKNOWN_ACCELERATOR_BVH_SPLIT_METHOD	  = 33,
		TPBRT_ERROR_UNKNOWN_SAMPLER_TYPE					  = 34,
		TPBRT_ERROR_UNKNOWN_SAMPLER_RANDOM					  = 35,
		TPBRT_ERROR_UNKNOWN_LIGHT_SOURCE_TYPE				  = 36,
		TPBRT_ERROR_UNKNOWN_AREA_LIGHT_TYPE					  = 37,
		TPBRT_ERROR_UNKNOWN_TEXTURE_TYPE					  = 38,
		TPBRT_ERROR_UNKNOWN_TEXTURE_CLASS					  = 39,
		TPBRT_ERROR_UNKNOWN_TEXTURE_WRAP					  = 40,
		TPBRT_ERROR_UNKNOWN_TEXTURE_FILTER					  = 41,
		TPBRT_ERROR_UNKNOWN_TEXTURE_ENCODING				  = 42,
		TPBRT_ERROR_UNKNOWN_TEXTURE_MAPPING					  = 43,
		TPBRT_ERROR_DUPLICATE_TEXTURE_NAME					  = 44,
		TPBRT_ERROR_INVALID_HANDLE							  = 45,
		TPBRT_ERROR_UNKNOWN_MATERIAL_TYPE					  = 46,
		TPBRT_ERROR_PARSE_STRING							  = 47,
		TPBRT_ERROR_UNKNOWN_SHAPE_TYPE						  = 48,
		TPBRT_ERROR_UNKNOWN_SHAPE_CURVE_BASIS				  = 49,
		TPBRT_ERROR_UNKNOWN_SHAPE_CURVE_TYPE				  = 50,
		TPBRT_ERROR_INVALID_PARAM_VALUE						  = 51,
		TPBRT_ERROR_UNKNOWN_MEDIA_TYPE						  = 52,
		TPBRT_ERROR_FILE_NOT_FOUND							  = 53,
		TPBRT_ERROR_DUPLICATE_OBJECT_NAME					  = 54,
		TPBRT_ERROR_UNKNOWN_FILTER_TYPE						  = 55,
		TPBRT_ERROR_MAX_NUM									  = 56,
	} tpbrt_error_t;

	tpbrt_size_t tpbrt_get_error_message(tpbrt_error_t error, tpbrt_char_t* buffer, tpbrt_size_t buffer_size);

#ifdef __cplusplus
}
#endif

#endif // _TINYPBRT_ERROR_H_
